### PR TITLE
Refactoring to classes PR

### PR DESCRIPTION
**Pull request by alef-garrido**
Project requirements:

- Use JavaScript classes instead of objects and arrays.
- You can use objects and arrays, but do it inside classes.
- Create class methods to add and remove books.
- Maintain all of the original functionality of the application (i.e. no bugs were introduced while refactoring).
- Don't use any library or framework, use only plain JavaScript.

### CODE REVIEW

**Review by dasileker — CHANGES_REQUESTED** [review]
### **Hi @alef-garrido** 

## **To highlight**

- Nice commit. 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._


- Please add linter workflows to your repo to make the action works see here 👉 [linter requirement ](https://user-images.githubusercontent.com/61562626/128946665-99746921-fb3e-4c3b-9b40-c6a89e4536b1.jpg)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alef-garrido** [comment]
> ### **Hi @alef-garrido**
> ## **To highlight**
> * Nice commit.
> 
> Good job so far!
> There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Required Changes 
> _Check the comments under the review._
> 
> * Please add linter workflows to your repo to make the action works see here point_right [linter requirement ](https://user-images.githubusercontent.com/61562626/128946665-99746921-fb3e-4c3b-9b40-c6a89e4536b1.jpg)
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

@dasileker Thank you for your time! I just want to ask you if you see any reasons for this issue? The configuration files are there, and the linters are running fine locally. Could this be a problem with GitHub?  Or we are doing something wrong?

**Comment by alef-garrido** [comment]
See here:

Opera Snapshot_2021-08-10_185317_github com
Opera Snapshot_2021-08-10_185627_github com

**Comment by dasileker** [comment]
Yes they are added but not working

**Comment by alef-garrido** [comment]
**That's why i asked you if you see any reasons for this error.**
We are supposed to add them, not fix them. 
Your feedback is not being helpful at all. 
Can you please share any hints on what to do? We didn't changed anything on those files.

**Review by carlos-ssh — APPROVED** [review]
Hello Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alef-garrido** [comment]
Refactoring the Awesome books application to use JavaScript classes.

**Pull request merged**
